name = "whenmeet-call-e2ee"

account_id = "9e7cfb40f9896e268a8212dc58e20780"
main = "./build/index.js"
# https://developers.cloudflare.com/workers/platform/compatibility-dates
compatibility_date = "2024-10-07"
compatibility_flags = ["nodejs_compat"]

[site]
  bucket = "./public"

[[build.upload.rules]]
type = "ESModule"
globs = ["**/*.js"]

[vars]
CALLS_APP_ID = "cf0b7d009feba7d66e94027f36d8d382"
CALLS_API_URL = "https://rtc.live.cloudflare.com"
TURN_SERVICE_ID = "3d47c5a790a0b730d98bf6ebf0e37553"
PUBLIC = "true"
E2EE_ENABLED = "true"

[[durable_objects.bindings]]
name = "rooms"
class_name = "ChatRoom"

# Indicate that you want the ChatRoom and RateLimiter classes to be callable as Durable Objects.
[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["ChatRoom", "RateLimiter"]

[[migrations]]
tag = "v2"
deleted_classes = ["RateLimiter"] 

# The necessary secrets are:
# - CALLS_APP_SECRET
# Run `echo <VALUE> | wrangler secret put <NAME>` for each of these


