name = "whenmeet-call"
account_id = "9e7cfb40f9896e268a8212dc58e20780"
# https://developers.cloudflare.com/workers/platform/compatibility-dates
compatibility_date = "2024-10-07"
main = "./build/index.js"
compatibility_flags = ["nodejs_compat"]

routes = [
  { pattern = "call.whenmeet.me", custom_domain = true }
]

[site]
  bucket = "./public"

[vars]
CALLS_APP_ID = "cf0b7d009feba7d66e94027f36d8d382"
CALLS_API_URL = "https://rtc.live.cloudflare.com"
TURN_SERVICE_ID = "3d47c5a790a0b730d98bf6ebf0e37553"
DEEPGRAM_ID = "417702fd-5dbd-402e-8516-fd05922c0d46"
OPENAI_MODEL_ENDPOINT = "https://api.openai.com/v1"
TRANSCRIPTION_PROVIDER = "openai"
TRANSCRIPTION_ENABLED = "false"
AI_INVITE_ENABLED = "false"
E2EE_ENABLED = "true"

[observability]
enabled = true

[observability.logs]
invocation_logs = true

[[durable_objects.bindings]]
name = "rooms"
class_name = "ChatRoom"

[[durable_objects.bindings]]
name = "transcriptionService"
class_name = "TranscriptionService"

# Indicate that you want the ChatRoom class to be callable as Durable Objects.
[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["ChatRoom"]

[[migrations]]
tag = "v2" # Should be unique for each entry
new_classes = ["TranscriptionService"]
