name: Checks

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  prerelease:
    timeout-minutes: 10
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - run: npm ci
      - run: npm run build

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium

      - name: Run all checks (lint, typecheck, unit tests, e2e tests)
        run: npm run check
